import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ApiClient, ApiError, getLogs } from './api/client';

type User = { id: string; email: string; role: 'ADMIN' | 'EXPERT' | 'REVIEWER' };
type Task = { id: string; title: string; instructions: string; status: string; project: { id: string; name: string }; assignments: { expertId: string }[]; submissions: Submission[]; reviews?: Review[] };
type Submission = { id: string; version: number; content: string; createdAt: string; submittedAt?: string | null };
type Criterion = { id: string; name: string; description?: string; minScore: string | number; maxScore: string | number; weight: string | number; position: number };
type Review = { id: string; reviewerId: string; submission: Submission & { task?: Task }; rubricVersion: { id: string; version: number; criteria: Criterion[] }; scores: { rubricCriterionId: string; score: string | number; comment?: string }[]; status: string };
type Project = { id: string; name: string; description?: string; tasks?: Task[]; rubrics?: { id: string; name: string }[] };

const seeded = { ADMIN: { email: 'admin@proxion.local', id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' }, EXPERT: { email: 'expert@proxion.local', id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' }, REVIEWER: { email: 'reviewer@proxion.local', id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc' } };
const initialCriteria = JSON.stringify([{ name: 'Accuracy', description: 'Claims are supported', minScore: 0, maxScore: 5, weight: 0.6, position: 1 }, { name: 'Clarity', description: 'Easy to follow', minScore: 0, maxScore: 5, weight: 0.4, position: 2 }], null, 2);
const fmt = (date?: string | null) => date ? new Date(date).toLocaleString() : '—';

function ErrorBanner({ error }: { error: ApiError | null }) { return error ? <div className="error"><strong>{error.status} · {error.code}</strong><span>{error.message}</span></div> : null; }
function Status({ value }: { value: string }) { return <span className={`status ${value.toLowerCase()}`}>{value.replace('_', ' ')}</span>; }
function Workflow({ current }: { current: string }) { const main = ['ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'IN_REVIEW', 'APPROVED']; return <div className="workflow"><div>{main.map((item, i) => <span key={item} className={item === current ? 'active' : ''}>{item.replace('_', ' ')}{i < main.length - 1 && <b>→</b>}</span>)}</div><small className={current === 'REWORK' ? 'active' : ''}>IN REVIEW → REWORK → IN PROGRESS</small></div>; }

export default function App() {
  const [session, setSession] = useState<{ token: string; user: User } | null>(() => { const value = localStorage.getItem('proxion-dev-session'); return value ? JSON.parse(value) : null; });
  const [tab, setTab] = useState('dashboard'); const [tasks, setTasks] = useState<Task[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [selectedTask, setSelectedTask] = useState<Task | null>(null); const [error, setError] = useState<ApiError | null>(null); const [busy, setBusy] = useState(false); const [logsOpen, setLogsOpen] = useState(false); const api = useMemo(() => new ApiClient(session?.token ?? null), [session]);
  const run = async <T,>(action: () => Promise<T>, reload = true): Promise<T | undefined> => { setBusy(true); setError(null); try { const value = await action(); if (reload) await refresh(); return value; } catch (e) { setError(e as ApiError); } finally { setBusy(false); } };
  const refresh = async () => { if (!session) return; const values = await Promise.all([api.get<Task[]>('/tasks'), session.user.role === 'ADMIN' ? api.get<Project[]>('/projects') : Promise.resolve([]), session.user.role === 'EXPERT' ? Promise.resolve([]) : api.get<Review[]>('/reviews')]); setTasks(values[0]); setProjects(values[1]); setReviews(values[2]); if (selectedTask) { const detail = await api.get<Task>(`/tasks/${selectedTask.id}`); setSelectedTask(detail); } };
  useEffect(() => { void run(async () => { await refresh(); }, false); }, [session]);
  const login = async (role: keyof typeof seeded) => { await run(async () => { const res = await new ApiClient(null).post<{ accessToken: string; user: User }>('/auth/login', { email: seeded[role].email, password: 'Password123!' }); const next = { token: res.accessToken, user: res.user }; localStorage.setItem('proxion-dev-session', JSON.stringify(next)); setSession(next); return res; }, false); };
  const logout = () => { localStorage.removeItem('proxion-dev-session'); setSession(null); setTasks([]); setProjects([]); setReviews([]); setSelectedTask(null); };
  const openTask = async (id: string) => { const task = await run(() => api.get<Task>(`/tasks/${id}`), false); if (task) { setSelectedTask(task); setTab('task'); } };
  if (!session) return <Login login={login} error={error} busy={busy} />;
  const nav = ['dashboard', ...(session.user.role === 'ADMIN' ? ['projects', 'audit'] : []), 'tasks', ...(session.user.role === 'REVIEWER' ? ['reviews'] : []), 'dev-tests'];
  return <main className="shell"><aside><div className="brand">PROXION <small>workflow tester</small></div><nav>{nav.map(item => <button key={item} onClick={() => setTab(item)} className={tab === item ? 'selected' : ''}>{item.replace('-', ' ')}</button>)}</nav><div className="side-note">Local-only test client<br/>Backend authorization stays authoritative.</div></aside><section className="page"><header><div><span className="eyebrow">INTERNAL DEVELOPMENT TOOL</span><h1>{tab === 'task' ? 'Task Debug View' : tab.replace('-', ' ')}</h1></div><div className="user"><span>{session.user.email}<small>{session.user.role}</small></span><button onClick={() => setLogsOpen(!logsOpen)} className="quiet">Developer</button><button onClick={logout} className="quiet">Logout</button></div></header><ErrorBanner error={error} />
    {tab === 'dashboard' && <Dashboard tasks={tasks} reviews={reviews} openTask={openTask} role={session.user.role} />}
    {tab === 'projects' && <AdminProjects api={api} projects={projects} run={run} openTask={openTask} />}
    {tab === 'tasks' && <Tasks tasks={tasks} openTask={openTask} role={session.user.role} />}
    {tab === 'task' && <TaskDetail task={selectedTask} api={api} role={session.user.role} run={run} openTask={openTask} />}
    {tab === 'reviews' && <Reviewer reviews={reviews} api={api} run={run} openTask={openTask} />}
    {tab === 'audit' && <Audit api={api} run={run} />}
    {tab === 'dev-tests' && <DevTests api={api} run={run} openTask={openTask} />}
    {logsOpen && <DeveloperPanel />}
    {busy && <div className="loading">Working…</div>}
  </section></main>;
}

function Login({ login, error, busy }: { login: (role: keyof typeof seeded) => Promise<void>; error: ApiError | null; busy: boolean }) { return <main className="login"><div className="login-card"><span className="eyebrow">LOCAL API EXERCISER</span><h1>Proxion<br/>Workflow Tester</h1><p>Use the seeded accounts to test the real REST API. Nothing here bypasses authorization.</p><ErrorBanner error={error}/>{(['ADMIN', 'EXPERT', 'REVIEWER'] as const).map(role => <button disabled={busy} key={role} className="login-role" onClick={() => void login(role)}><strong>Login as {role[0] + role.slice(1).toLowerCase()}</strong><small>{seeded[role].email}</small></button>)}<small className="hint">Password: Password123!</small></div></main>; }
function Dashboard({ tasks, reviews, openTask, role }: { tasks: Task[]; reviews: Review[]; openTask: (id: string) => void; role: string }) { return <><div className="metrics"><Metric label="Visible tasks" value={tasks.length}/><Metric label={role === 'REVIEWER' ? 'Assigned reviews' : 'In progress'} value={role === 'REVIEWER' ? reviews.length : tasks.filter(t => t.status === 'IN_PROGRESS').length}/><Metric label="Awaiting review" value={tasks.filter(t => t.status === 'SUBMITTED' || t.status === 'IN_REVIEW').length}/></div><section className="card"><h2>Recent work</h2><TaskTable tasks={tasks.slice(0, 6)} openTask={openTask}/></section></>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function TaskTable({ tasks, openTask }: { tasks: Task[]; openTask: (id: string) => void }) { return <table><thead><tr><th>Task</th><th>Project</th><th>Status</th><th>Versions</th><th/></tr></thead><tbody>{tasks.map(t => <tr key={t.id}><td><strong>{t.title}</strong><small className="mono">{t.id}</small></td><td>{t.project.name}</td><td><Status value={t.status}/></td><td>{t.submissions?.length ?? 0}</td><td><button className="link" onClick={() => void openTask(t.id)}>Inspect</button></td></tr>)}{!tasks.length && <tr><td colSpan={5} className="empty">No resources visible to this role.</td></tr>}</tbody></table>; }
function Tasks({ tasks, openTask, role }: { tasks: Task[]; openTask: (id: string) => void; role: string }) { return <section className="card"><div className="split"><div><h2>{role === 'EXPERT' ? 'Assigned tasks' : 'Tasks'}</h2><p>Visibility comes from the backend assignment checks.</p></div><label className="id-entry">Open any task ID <TaskFinder openTask={openTask}/></label></div><TaskTable tasks={tasks} openTask={openTask}/></section>; }
function TaskFinder({ openTask }: { openTask: (id: string) => void }) { const [id, setId] = useState(''); return <span><input value={id} onChange={e => setId(e.target.value)} placeholder="UUID"/><button onClick={() => void openTask(id)}>Open</button></span>; }
function AdminProjects({ api, projects, run, openTask }: { api: ApiClient; projects: Project[]; run: <T>(fn: () => Promise<T>) => Promise<T | undefined>; openTask: (id: string) => void }) {
  const [projectId, setProjectId] = useState(''); const [rubricId, setRubricId] = useState(''); const [criteria, setCriteria] = useState(initialCriteria);
  const submit = (event: FormEvent<HTMLFormElement>, action: (data: FormData) => Promise<unknown>) => { event.preventDefault(); void run(() => action(new FormData(event.currentTarget))); };
  return <div className="stack"><section className="card"><h2>Projects</h2><form className="inline-form" onSubmit={e => submit(e, d => api.post('/projects', { name: d.get('name'), description: d.get('description') }))}><input name="name" required placeholder="Project name"/><input name="description" placeholder="Description"/><button>Create project</button></form><table><thead><tr><th>Name</th><th>Description</th><th>Tasks</th></tr></thead><tbody>{projects.map(p => <tr key={p.id}><td><strong>{p.name}</strong><small className="mono">{p.id}</small></td><td>{p.description || '—'}</td><td>{p.tasks?.length ?? '—'}</td></tr>)}</tbody></table></section>
  <section className="card"><h2>Create task & assign expert</h2><p>Use a project UUID from the table. The default expert is the seeded expert account.</p><form className="form-grid" onSubmit={e => submit(e, async d => { const task = await api.post<Task>(`/projects/${d.get('projectId')}/tasks`, { title: d.get('title'), instructions: d.get('instructions') }); await api.post(`/tasks/${task.id}/assign`, { expertId: d.get('expertId') }); return task; })}><input name="projectId" required placeholder="Project UUID" value={projectId} onChange={e => setProjectId(e.target.value)}/><input name="title" required placeholder="Task title"/><textarea name="instructions" required placeholder="Instructions"/><input name="expertId" required defaultValue={seeded.EXPERT.id}/><button>Create and assign</button></form></section>
  <section className="card"><h2>Rubrics</h2><p>Creating a rubric creates version 1 with these criteria. Add later versions without changing historical reviews.</p><textarea value={criteria} onChange={e => setCriteria(e.target.value)} rows={9}/><form className="inline-form" onSubmit={e => submit(e, d => api.post(`/projects/${d.get('projectId')}/rubrics`, { name: d.get('name'), criteria: JSON.parse(criteria) }))}><input name="projectId" required placeholder="Project UUID"/><input name="name" required placeholder="Rubric name"/><button>Create rubric v1</button></form><form className="inline-form top-gap" onSubmit={e => submit(e, d => api.post(`/rubrics/${d.get('rubricId')}/versions`, { criteria: JSON.parse(criteria) }))}><input name="rubricId" required placeholder="Existing rubric UUID" value={rubricId} onChange={e => setRubricId(e.target.value)}/><button>Create next version</button></form></section>
  <section className="card"><h2>Quick task inspection</h2><TaskTable tasks={projects.flatMap(p => p.tasks ?? [])} openTask={openTask}/></section></div>;
}
function TaskDetail({ task, api, role, run, openTask }: { task: Task | null; api: ApiClient; role: User['role']; run: <T>(fn: () => Promise<T>) => Promise<T | undefined>; openTask: (id: string) => void }) {
  const [content, setContent] = useState(''); const [reviewerId, setReviewerId] = useState(seeded.REVIEWER.id); const [rubricVersionId, setRubricVersionId] = useState('');
  if (!task) return <section className="card"><h2>Open a task</h2><TaskFinder openTask={openTask}/></section>;
  const action = (path: string) => void run(() => api.post(path));
  return <div className="stack"><section className="card task-head"><div><span className="eyebrow">{task.project.name}</span><h2>{task.title}</h2><p>{task.instructions}</p><small className="mono">{task.id}</small></div><Status value={task.status}/></section><section className="card"><h3>Workflow</h3><Workflow current={task.status}/><div className="actions">{role === 'EXPERT' && <><button onClick={() => action(`/tasks/${task.id}/start`)}>Start work</button><button onClick={() => action(`/tasks/${task.id}/submit`)}>Submit latest</button></>}{role === 'REVIEWER' && <><button onClick={() => action(`/tasks/${task.id}/request-rework`)}>Request rework</button><button onClick={() => action(`/tasks/${task.id}/approve`)}>Approve</button></>}</div></section>
  {role === 'EXPERT' && <section className="card"><h3>Create a new immutable submission version</h3><p>This always creates a new version; it never edits an old one.</p><textarea value={content} onChange={e => setContent(e.target.value)} placeholder="Submission content" rows={6}/><button disabled={!content} onClick={() => { void run(() => api.post(`/tasks/${task.id}/submissions`, { content })); setContent(''); }}>Create submission</button></section>}
  {role === 'ADMIN' && <section className="card"><h3>Assign a reviewer / create review</h3><p>Creating the review moves a submitted task into review.</p><div className="inline-form"><input value={reviewerId} onChange={e => setReviewerId(e.target.value)} placeholder="Reviewer UUID"/><input value={rubricVersionId} onChange={e => setRubricVersionId(e.target.value)} placeholder="Rubric version UUID"/><button disabled={!task.submissions?.[0] || !rubricVersionId} onClick={() => void run(() => api.post(`/submissions/${task.submissions[0].id}/reviews`, { reviewerId, rubricVersionId }))}>Create review for latest</button></div></section>}
  <section className="card"><h3>Submission history</h3><div className="versions">{task.submissions?.map(s => <article key={s.id}><div><strong>Submission v{s.version}</strong><small>Created {fmt(s.createdAt)} · Submitted {fmt(s.submittedAt)}</small></div><pre>{s.content}</pre></article>)}{!task.submissions?.length && <p className="empty">No submissions yet.</p>}</div></section>
  {role !== 'EXPERT' && <section className="card"><h3>Reviews & pinned rubric versions</h3>{task.reviews?.map(review => <article className="review-summary" key={review.id}><strong>Review {review.id}</strong><span>Rubric v{review.rubricVersion.version} · Submission v{review.submission.version}</span><ul>{review.rubricVersion.criteria.map(c => { const score = review.scores.find(s => s.rubricCriterionId === c.id); return <li key={c.id}>{c.name}: {score ? `${score.score} — ${score.comment ?? ''}` : 'not scored'}</li>; })}</ul></article>) || <p className="empty">No reviews visible.</p>}</section>}</div>;
}
function Reviewer({ reviews, api, run, openTask }: { reviews: Review[]; api: ApiClient; run: <T>(fn: () => Promise<T>) => Promise<T | undefined>; openTask: (id: string) => void }) { const [scores, setScores] = useState<Record<string, { score: string; comment: string }>>({}); return <div className="stack">{reviews.map(r => { const task = r.submission.task; return <section className="card" key={r.id}><div className="split"><div><span className="eyebrow">{task?.project?.name ?? 'Assigned review'}</span><h2>{task?.title ?? `Submission v${r.submission.version}`}</h2><p>Submission v{r.submission.version} · Rubric v{r.rubricVersion.version}</p></div><button onClick={() => task && void openTask(task.id)}>Task detail</button></div><pre>{r.submission.content}</pre><div className="score-grid">{r.rubricVersion.criteria.map(c => { const saved = r.scores.find(s => s.rubricCriterionId === c.id); const value = scores[c.id] ?? { score: String(saved?.score ?? ''), comment: saved?.comment ?? '' }; return <div key={c.id} className="score-row"><strong>{c.position}. {c.name}</strong><small>{c.description} · {String(c.minScore)}–{String(c.maxScore)}</small><input type="number" min={Number(c.minScore)} max={Number(c.maxScore)} value={value.score} onChange={e => setScores({ ...scores, [c.id]: { ...value, score: e.target.value } })} placeholder="Score"/><input value={value.comment} onChange={e => setScores({ ...scores, [c.id]: { ...value, comment: e.target.value } })} placeholder="Comment"/><button disabled={!value.score} onClick={() => void run(() => api.put(`/reviews/${r.id}/scores/${c.id}`, { score: Number(value.score), comment: value.comment }))}>Save score</button></div>; })}</div><div className="actions"><button onClick={() => task && void run(() => api.post(`/tasks/${task.id}/request-rework`))}>Request rework</button><button onClick={() => task && void run(() => api.post(`/tasks/${task.id}/approve`))}>Approve</button></div></section>; })}{!reviews.length && <section className="card empty">No assigned reviews. An admin must create one for a submitted task.</section>}</div>; }
function Audit({ api, run }: { api: ApiClient; run: <T>(fn: () => Promise<T>) => Promise<T | undefined> }) { const [records, setRecords] = useState<any[]>([]); const [filter, setFilter] = useState(''); useEffect(() => { void run(async () => { const data = await api.get<any[]>('/audit-logs?limit=100'); setRecords(data); return data; }); }, []); const visible = records.filter(r => !filter || [r.entityType, r.entityId, r.actorId, r.action].join(' ').toLowerCase().includes(filter.toLowerCase())); return <section className="card"><div className="split"><div><h2>Audit log</h2><p>Append-only workflow and score changes from the API.</p></div><input value={filter} onChange={e => setFilter(e.target.value)} placeholder="Filter type, ID, actor, action"/></div><div className="audit-table"><table><thead><tr><th>Timestamp</th><th>Actor</th><th>Entity</th><th>Action</th><th>Before</th><th>After</th><th>Request ID</th></tr></thead><tbody>{visible.map(r => <tr key={r.id}><td>{fmt(r.createdAt)}</td><td className="mono">{r.actorId}</td><td>{r.entityType}<small className="mono">{r.entityId}</small></td><td>{r.action}</td><td><code>{JSON.stringify(r.before)}</code></td><td><code>{JSON.stringify(r.after)}</code></td><td className="mono">{r.requestId ?? '—'}</td></tr>)}{!visible.length && <tr><td colSpan={7} className="empty">No matching audit entries.</td></tr>}</tbody></table></div></section>; }
function DevTests({ api, run, openTask }: { api: ApiClient; run: <T>(fn: () => Promise<T>) => Promise<T | undefined>; openTask: (id: string) => void }) { const [id, setId] = useState(''); return <div className="stack"><section className="card danger"><span className="eyebrow">DEV TEST ONLY</span><h2>Send an intentionally invalid transition</h2><p>This does not implement client-side workflow validation. It calls the actual approve endpoint so the backend should reject an invalid state with a visible 409 response.</p><div className="inline-form"><input value={id} onChange={e => setId(e.target.value)} placeholder="Task UUID (e.g. an ASSIGNED task)"/><button onClick={() => void run(() => api.post(`/tasks/${id}/approve`))}>Attempt approve</button></div></section><section className="card"><h2>RBAC isolation probe</h2><p>Enter any task UUID while logged in as an expert or reviewer. The request is sent; a backend 403 is shown above if the task is not assigned to you.</p><div className="inline-form"><input value={id} onChange={e => setId(e.target.value)} placeholder="Task UUID"/><button onClick={() => void openTask(id)}>Fetch task</button></div></section></div>; }
function DeveloperPanel() { const logs = getLogs(); return <section className="developer"><h3>Developer · recent API calls</h3>{logs.map((log, i) => <details key={`${log.at}-${i}`}><summary><b>{log.status}</b> {log.method} {log.url} <small>{fmt(log.at)}</small></summary><pre>{JSON.stringify({ request: log.body, response: log.response }, null, 2)}</pre></details>)}{!logs.length && <p>No requests recorded in this browser yet.</p>}</section>; }
